---
- name: Variables in Ansible
  hosts: webserver
  become: yes

  vars:
    course: DevOps
    trainer: Jana
    duration: '3 months'

  tasks:
    - name: Print hello world
      ansible.builtin.debug:
        msg: 'Hello, I am Ansible'

    - name: Print the variables
      ansible.builtin.debug:
        msg: 'The course is {{ course }}, the trainer is {{ trainer }}, and the duration is {{ duration }}'
