---
- name: ansibel conditions
  hosts: webserver
  become: yes

  tasks:
    - name: check the os family
      ansible.builtin.debug:
        msg: 'The OS is {{ ansible_distribution }}'

    - name: Install nginx only on Ububtu
      ansible.builtin.apt:
        name: nginx
        state: preset
      when: ansible_distribution = "Ubunut"
